name: Code Quality Checks

on:
  pull_request:
  push:
    branches:
    - main

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint: #-----------------------------------------------------------------------
    name: Lint PHP files
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v5

    - name: Set up PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'
        tools: cs2pr
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Composer dependencies & cache dependencies
      uses: "ramsey/composer-install@v3"
      env:
        COMPOSER_ROOT_VERSION: dev-${{ github.event.repository.default_branch }}

    - name: Run Linter
      run: vendor/bin/parallel-lint -j 10 . --exclude vendor --checkstyle | cs2pr

  phpcs: #----------------------------------------------------------------------
    name: PHPCS
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v5

    - name: Set up PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: 'latest'
        tools: cs2pr
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Composer dependencies & cache dependencies
      uses: "ramsey/composer-install@v3"
      env:
        COMPOSER_ROOT_VERSION: dev-${{ github.event.repository.default_branch }}

    - name: Run PHPCS
      run: vendor/bin/phpcs -q --report=checkstyle | cs2pr
